### ISSUE TITLE
Which information I need to insert on URI field?

### ISSUE THREAD

**Issue by brnyza** [AprilBrother/ab-ble-gateway-sdk#4]
![image](https://user-images.githubusercontent.com/4684660/123869136-ff3ab200-d906-11eb-9568-52e9dadf6284.png)

**Comment by brnyza** [comment]
I saw that I can insert any information

**Comment by volca** [comment]
Thanks for update. But here's [the repo the config tool](https://github.com/AprilBrother/gw4-config-tool).
